### PR TITLE
Class name for Download Link

### PR DESCRIPTION
**Pull request by X-Raym**
Add a class name to download link to allow styling.
Better than ID in case of multiple download :)

### CODE REVIEW

**Comment by pasqLisena** [comment]
Please describe this in the README :pray: :smile:

**Comment by rndme** [comment]
there's not a good place in the readme for that single tidbit to go, but i'll see about adding a new section with that included. i'd like to answer a few other common questions, so maybe a FAQ is apropos... at any rate, yeah, good idea; i'll think about it and see what i can do.

**Comment by rndme** [comment]
@pasqLisena : i added a FAQ section with that information included. It's not the most prominent, but it is there. thanks again for the idea.

**Comment by pasqLisena** [comment]
Thank you for having added :+1: :smile:

**Pull request merged**
